### ISSUE TITLE
This sample is out of date and has breaking changes following MSAL.NET v4

### ISSUE THREAD

**Issue by patrickjlee** [Azure-Samples/active-directory-dotnet-admin-restricted-scopes-v2#23]
When you build this sample with MSAL.NET v4, you now get 10 warnings, most of which are due to this breaking change made in MSAL.NET v4:

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/msal-net-4#a-breaking-change:
ITokenCache's responsibility splatted between ITokenCache and ITokenCacheSerializer

And if you try and run the code, you now get run time errors because of this. 

And it doesn't seem obvious how to correct the code to allow for MSAL.NET v4.

Because this is still held up as a current sample at https://docs.microsoft.com/en-us/azure/active-directory/develop/sample-v2-code, I think this sample should be updated so that it works again please?

**Comment by jmprieur** [comment]
@kalyankrishna1 @TiagoBrenck 
We'd wantt o update the code from more recent copies of Microsoft.Identity.Web.

**Comment by TiagoBrenck** [comment]
I will take this task.
