### ISSUE TITLE
Compile error: "App_Start\BundleConfig.cs".GetPathsOfAllDirectoriesAbove()" cannot be evaluated. Method 'System.String.GetPathsOfAllDirectoriesAbove' not found.

### ISSUE THREAD

**Issue by phuong-vo** [Azure-Samples/active-directory-dotnet-admin-restricted-scopes-v2#29]
I checked out active-directory-dotnet-admin-restricted-scopes-v2 master branch and open in Microsot Visual Studio Enterprise 2017 on Windows Server 2016 Standard, but I got the errors below. What did I miss? 

`

Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Error |   | The expression ""App_Start\BundleConfig.cs".GetPathsOfAllDirectoriesAbove()" cannot be evaluated. Method 'System.String.GetPathsOfAllDirectoriesAbove' not found. | GroupManager |   |   |  

`

**Comment by jmprieur** [comment]
@TiagoBrenck : do you mind having a look?

**Comment by TiagoBrenck** [comment]
@phuong-vo I couldn't reproduce this error, and I couldn't even find this `GetPathsOfAllDirectoriesAbove()` method. This kind of error sounds like missing a .NET framework version. This sample is using **.NET 4.7.2**. Could you please check if you have it installed?

Then, also try cleaning the solution. Let me know if it worked.

**Comment by Arlorean** [comment]
I'm not doing anything with Azure but I just got this error when trying to use the latest Roslyn C# compiler. It comes with some updated .targets files that require a new version of MSBuild that isn't compatible with Visual Studio 2017. You'll probably have to upgrade to Visual Studio 2019:
[GetPathsOfAllDirectoriesAbove error on visualstudio.com](https://developercommunity.visualstudio.com/content/problem/815463/method-systemstringgetpathsofalldirectoriesabove-n.html?childToView=891777#comment-891777)

**Comment by ghost** [comment]
> I checked out active-directory-dotnet-admin-restricted-scopes-v2 master branch and open in Microsot Visual Studio Enterprise 2017 on Windows Server 2016 Standard, but I got the errors below. What did I miss? 
> 
> 
> 
> `
> 
> 
> 
> Severity | Code | Description | Project | File | Line | Suppression State
> 
> -- | -- | -- | -- | -- | -- | --
> 
> Error |   | The expression ""App_Start\BundleConfig.cs".GetPathsOfAllDirectoriesAbove()" cannot be evaluated. Method 'System.String.GetPathsOfAllDirectoriesAbove' not found. | GroupManager |   |   |  
> 
> 
> 
> `

**Comment by ghost** [comment]
> I checked out active-directory-dotnet-admin-restricted-scopes-v2 master branch and open in Microsot Visual Studio Enterprise 2017 on Windows Server 2016 Standard, but I got the errors below. What did I miss? 
> 
> 
> 
> `
> 
> 
> 
> Severity | Code | Description | Project | File | Line | Suppression State
> 
> -- | -- | -- | -- | -- | -- | --
> 
> Error |   | The expression ""App_Start\BundleConfig.cs".GetPathsOfAllDirectoriesAbove()" cannot be evaluated. Method 'System.String.GetPathsOfAllDirectoriesAbove' not found. | GroupManager |   |   |  
> 
> 
> 
> `

**Comment by ghost** [comment]
[]()

**Comment by kalyankrishna1** [comment]
no further action needed
