### ISSUE TITLE
Consumer accounts are not supported for the Group Manager App. Please log in with your work account.

### ISSUE THREAD

**Issue by ravisheee** [Azure-Samples/active-directory-dotnet-admin-restricted-scopes-v2#9]
Hi there,
I have an AAD admin account and trying to run this sample, but getting below error. Could you please guide me about this error.
**Consumer accounts are not supported for the Group Manager App. Please log in with your work account.**

The account which I am using to login is a work account [ravish@nelsonhardiman.com]

Thanks
Ravish

**Comment by jmprieur** [comment]
This sample is about groups and users, which only make sense in context of AAD accounts (work and school accounts). this is by design that Microsoft Personal accounts (live / skype / XBox / accounts) are not supported
